repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        exclude: (vendor/.*)
      - id: check-toml
        exclude: (vendor/.*)
      - id: check-yaml
        exclude: (vendor/.*)
      - id: end-of-file-fixer
        exclude: (vendor/.*)
      - id: mixed-line-ending
        exclude: (vendor/.*)
      - id: trailing-whitespace
        exclude: (vendor/.*)

  - repo: local
    hooks:
      - id: format
        name: format code
        entry: make format
        language: system
        always_run: true

      - id: lint
        name: check code style
        entry: make lint
        language: system
        always_run: true

      - id: test
        name: run tests
        entry: make test
        language: system
        always_run: true

      - id: build
        name: build project
        entry: make build
        language: system
        always_run: true
